apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop-prod
resources:
  - ../../base
  - httproute.yaml
labels:
  - pairs: {environment: prod}
    includeSelectors: false
patches:
  - target: {kind: Deployment, name: shop}
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
